# !!!!!! very important to do the below tasks before any release is done
# 1. run bootstrap.sh in the real git
# 2. run make maintainer-all
# 3. zip the tree with:
#    zip -9r ../autoconf-archive Makefile.in Makefile.am m4 configure \
#        AUTHORS ChangeLog NEWS README TODO m4 doc build-aux/install-sh \
#        build-aux/missing configure.ac aclocal.m4 build-aux/mdate.sh COPYING*
# 4. copy it to your sources
# 5. build the rpm


Name:           autoconf-archive
Version:        2019.01.06
Release:        1%{?dist}
Summary:        The Autoconf Macro Archive
License:        GPLv3+ with exceptions
URL:            http://www.gnu.org/software/autoconf-archive/
Source0:        autoconf-archive.zip
Vendor:         bww bitwise works GmbH
BuildArch:      noarch
Requires:       autoconf

%description
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.

%prep
%setup -c -q

%build
%configure
make

%install
%make_install INSTALL="install -p"
# remove dir file which will be generated by /sbin/install-info
rm -frv %{buildroot}%{_infodir}/dir
# document files are installed another location
rm -frv %{buildroot}%{_datadir}/doc/%{name}

%files
%doc AUTHORS NEWS README TODO
%license COPYING*
%{_datadir}/aclocal/*.m4
%{_infodir}/autoconf-archive.info*

%changelog
* Fri Dec 13 2019 Silvan Scherrer <silvan.scherrer@aroa.ch> 2019.01.06-1
- initial OS/2 rpm
