%if 0%{?os2_version}
# !!!!!! very important to do the below tasks before any release is done
# 1. run bootstrap.sh in the real git
# 2. run configure
# 3. run make maintainer-all
# 4. zip the tree with:
#    zip -9r ../autoconf-archive Makefile.in Makefile.am m4 configure \
#        AUTHORS ChangeLog NEWS README TODO m4 doc build-aux/install-sh \
#        build-aux/missing configure.ac aclocal.m4 build-aux/mdate-sh COPYING*
# 5. copy it to your sources
# 6. build the rpm
%endif

Name:           autoconf-archive
Version:        2024.10.16
Release:        1%{?dist}
Summary:        The Autoconf Macro Archive

# The following licenses were seen in the binary rpm.
# We only try to make an exhaustive list, not to decide what is to be applied.
License:        GPL-2.0-or-later WITH Autoconf-exception-macro AND GPL-3.0-or-later AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-or-later WITH Autoconf-exception-macro AND GFDL-1.3-or-later AND LGPL-3.0-or-later WITH Autoconf-exception-macro AND LGPL-2.1-or-later AND BSD-2-Clause AND BSD-3-Clause AND FSFAP AND FSFAP-no-warranty-disclaimer AND FSFULLR
URL:            https://www.gnu.org/software/autoconf-archive/
%if !0%{?os2_version}
Source0:        https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz
Source1:        https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz.sig
# gpg --keyserver pool.sks-keyservers.net --recv-keys 1A4F63A13A4649B632F65EE141BC28FE99089D72
# gpg --export --export-options export-minimal 1A4F63A13A4649B632F65EE141BC28FE99089D72 > gpgkey-1A4F63A13A4649B632F65EE141BC28FE99089D72.gpg
Source2:        gpgkey-1A4F63A13A4649B632F65EE141BC28FE99089D72.gpg
%else
Source0:        autoconf-archive.zip
Vendor:         bww bitwise works GmbH
%endif
BuildArch:      noarch
%if !0%{?os2_version}
BuildRequires:  gnupg2
%endif
BuildRequires:  make
Requires:       autoconf

%description
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.

%prep
%if !0%{?os2_version}
%{gpgverify} --keyring='%{SOURCE2}' --signature='%{SOURCE1}' --data='%{SOURCE0}'
%autosetup -p1
%else
%setup -c -q
%endif

%build
%configure
%make_build

%install
%make_install
# remove dir file which will be generated by /sbin/install-info
rm -frv %{buildroot}%{_infodir}/dir
# document files are installed another location
rm -frv %{buildroot}%{_datadir}/doc/%{name}

%files
%doc AUTHORS NEWS README TODO
%license COPYING*
%{_datadir}/aclocal/*.m4
%{_infodir}/autoconf-archive.info*

%changelog
* Fri May 02 2025 Silvan Scherrer <silvan.scherrer@aroa.ch> 2024.10.16-1
- update to version 2024.10.16

* Fri Dec 13 2019 Silvan Scherrer <silvan.scherrer@aroa.ch> 2019.01.06-1
- initial OS/2 rpm
