Summary: The GNU versions of find utilities (find and xargs)
Name: findutils
Version: 4.4.2
Release: 1%{?dist}
Epoch: 1
License: GPLv3+
Group: Applications/File
URL: http://www.gnu.org/software/findutils/
Source0: ftp://ftp.gnu.org/gnu/findutils/%{name}-%{version}.tar.gz

Patch0: findutils-os2.patch

Buildroot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
#BuildRequires: libtool, automake, autoconf
#BuildRequires: dejagnu, texinfo
BuildRequires: gettext-devel

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a file name pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%prep
%setup -q
%patch0 -p1

%build
export CONFIG_SHELL="/@unixroot/usr/bin/sh.exe"
export CFLAGS="$RPM_OPT_FLAGS -D_GNU_SOURCE"
export LDFLAGS="-Zbin-files -Zhigh-mem -Zomf -Zargs-wild -Zargs-resp"
export LIBS="-lurpo -lmmap"
%configure \
   "--cache-file=%{_topdir}/cache/%{name}-%{_target_cpu}.cache"
make %{?_smp_mflags}

#%check
#make check

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT

rm -f $RPM_BUILD_ROOT%{_infodir}/dir
rm -f $RPM_BUILD_ROOT/%{_libdir}/charset.alias

#%find_lang %{name}

# move find to /bin/find
#mkdir -p $RPM_BUILD_ROOT/bin
#mv $RPM_BUILD_ROOT{%_bindir,/bin}/find

# create /usr/bin/find -> /bin/find symlink
#ln -sf ../../bin/find $RPM_BUILD_ROOT/usr/bin

%clean
rm -rf $RPM_BUILD_ROOT

%files
# -f %{name}.lang
%defattr(-,root,root,-)
%doc AUTHORS COPYING NEWS README THANKS TODO
%{_bindir}/find.exe
%{_bindir}/oldfind.exe
%{_bindir}/xargs.exe
%{_bindir}/locate.exe
%{_bindir}/updatedb
%{_libexecdir}/*
%{_mandir}/man1/*
%{_mandir}/man5/*
%{_infodir}/find.info*
%{_infodir}/find-maint.info
%{_datadir}/locale/*

%changelog
* Sun Jan 08 2012 yd
- initial unixroot build.
