#define svn_url     e:/trees/findutils/trunk
%define svn_url     http://svn.netlabs.org/repos/ports/findutils/trunk
%define svn_rev     1746

Summary: The GNU versions of find utilities (find and xargs)
Name: findutils
Version: 4.6.0
Release: 2%{?dist}
Epoch: 1
License: GPLv3+
Group: Applications/File
URL: http://www.gnu.org/software/findutils/
Vendor:  bww bitwise works GmbH
Source:  %{name}-%{version}%{?svn_rev:-r%{svn_rev}}.zip

Buildroot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires: libtool, automake, autoconf
BuildRequires: texinfo
#BuildRequires: dejagnu

#Requires(post): /sbin/install-info
#Requires(preun): /sbin/install-info

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a file name pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%debug_package

%prep
%if %{?svn_rev:%(sh -c 'if test -f "%{_sourcedir}/%{name}-%{version}-r%{svn_rev}.zip" ; then echo 1 ; else echo 0 ; fi')}%{!?svn_rev):0}
%setup -q
%else
%setup -n "%{name}-%{version}" -Tc
svn export %{?svn_rev:-r %{svn_rev}} %{svn_url} . --force
rm -f "%{_sourcedir}/%{name}-%{version}%{?svn_rev:-r%{svn_rev}}.zip"
(cd .. && zip -SrX9 "%{_sourcedir}/%{name}-%{version}%{?svn_rev:-r%{svn_rev}}.zip" "%{name}-%{version}")
%endif

autoreconf -fiv

%build
export LDFLAGS="-Zhigh-mem -Zomf -Zargs-wild -Zargs-resp"
export LIBS="-lcx -lpthread"
%configure

make %{?_smp_mflags}

#%check
#make check

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT

rm -f %{buildroot}%{_infodir}/dir

# yd move conflicting tools to libexec/bin and place a symlink for script compatibility
mkdir -p $RPM_BUILD_ROOT%{_libexecdir}/bin
for i in find; do
  mv $RPM_BUILD_ROOT%{_bindir}/$i.exe $RPM_BUILD_ROOT%{_libexecdir}/bin/$i.exe
  ln -s %{_libexecdir}/bin/$i.exe $RPM_BUILD_ROOT%{_bindir}/$i
done

%find_lang %{name}

%post
#if [ -f %{_infodir}/find.info.gz ]; then
#  /sbin/install-info %{_infodir}/find.info.gz %{_infodir}/dir || :
#fi

%preun
#if [ $1 = 0 ]; then
#  if [ -f %{_infodir}/find.info.gz ]; then
#    /sbin/install-info --delete %{_infodir}/find.info.gz %{_infodir}/dir || :
#  fi
#fi

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{name}.lang
%defattr(-,root,root,-)
%{!?_licensedir:%global license %%doc}
%license COPYING
%doc AUTHORS NEWS README THANKS TODO
%{_bindir}/find
%{_bindir}/xargs.exe
%{_bindir}/locate.exe
%{_bindir}/updatedb
%{_libexecdir}/*
%{_mandir}/man1/*
%{_mandir}/man5/*
%{_infodir}/find.info*
%{_infodir}/find-maint.info
%{_datadir}/locale/*
%exclude %{_libexecdir}/*.dbg
%exclude %{_libexecdir}/bin/*.dbg

%changelog
* Mon Oct 24 2016 Silvan Scherrer <silvan.scherrer@aroa.ch> - 4.6.0-2
- fix locate --statistics
- use ; as path seperator

* Wed Oct 05 2016 Silvan Scherrer <silvan.scherrer@aroa.ch> - 4.6.0-1
- udated version to 4.6.0
- adjusted spec to latest toolset

* Sat Mar 15 2014 yd
- fixed libexec dir for symlinks.
- added debug package with symbolic info for exceptq.

* Tue Jul 30 2013 yd
- disabled FTS code, now find works as before.

* Wed Jul 24 2013 yd
- move conflicting tools to libexec/bin.

* Wed Jun 05 2013 yd
- r641, fix xargs stop in freadahead.

* Thu Mar 14 2013 yd
- rename find.exe to find-unix.exe and add symlink.

* Sun Jan 08 2012 yd
- initial unixroot build
