# Note: this .spec is borrowed from libtool-2.4.2-21.fc20.src.rpm

%global gcc_version 4.7.3

Summary: The GNU Portable Library Tool
Name:    libtool
Version: 2.4.2
Release: 4%{?dist}
License: GPLv2+ and LGPLv2+ and GFDL
URL:     http://www.gnu.org/software/libtool/
Group:   Development/Tools

#Source:  http://ftp.gnu.org/gnu/libtool/libtool-%{version}.tar.xz

%define svn_url     http://svn.netlabs.org/repos/ports/libtool/trunk
%define svn_rev     846

Source: %{name}-%{version}-r%{svn_rev}.zip

BuildRequires: gcc make subversion zip

#Requires(post):  /sbin/install-info
#Requires(preun): /sbin/install-info

BuildRequires: autoconf, automake
#BuildRequires: texinfo
Requires: autoconf, automake, sed, tar

# make sure we can configure all supported langs
#BuildRequires: libstdc++-devel, gcc-gfortran

# /usr/bin/libtool includes paths within gcc's versioned directories
# Libtool must be rebuilt whenever a new upstream gcc is built
Requires: gcc >= %{gcc_version}
Requires: gcc <= %{gcc_version}.999

%description
GNU Libtool is a set of shell scripts which automatically configure UNIX and
UNIX-like systems to generically build shared libraries. Libtool provides a
consistent, portable interface which simplifies the process of using shared
libraries.

If you are developing programs which will use shared libraries, but do not use
the rest of the GNU Autotools (such as GNU Autoconf and GNU Automake), you
should install the libtool package.

The libtool package also includes all files needed to integrate the GNU
Portable Library Tool (libtool) and the GNU Libtool Dynamic Module Loader
(ltdl) into a package built using the GNU Autotools (including GNU Autoconf
and GNU Automake).

%package ltdl
Summary:  Runtime libraries for GNU Libtool Dynamic Module Loader
Group:    System Environment/Libraries
Provides: %{name}-libs = %{version}-%{release}
License:  LGPLv2+

%description ltdl
The libtool-ltdl package contains the GNU Libtool Dynamic Module Loader, a
library that provides a consistent, portable interface which simplifies the
process of using dynamic modules.

These runtime libraries are needed by programs that link directly to the
system-installed ltdl libraries; they are not needed by software built using
the rest of the GNU Autotools (including GNU Autoconf and GNU Automake).

%package ltdl-devel
Summary: Tools needed for development using the GNU Libtool Dynamic Module Loader
Group:    Development/Libraries
Requires: %{name}-ltdl = %{version}-%{release}
License:  LGPLv2+

%description ltdl-devel
Static libraries and header files for development with ltdl.

%package debug
Summary: HLL debug data for exception handling support.

%description debug
HLL debug data for exception handling support.

%prep
%if %(sh -c 'if test -f "%{_sourcedir}/%{name}-%{version}-r%{svn_rev}.zip" ; then echo 1 ; else echo 0 ; fi')
%setup -q
%else
%setup -n "%{name}-%{version}" -Tc
svn export -r %{svn_rev} %{svn_url} . --force
rm -f "%{_sourcedir}/%{name}-%{version}-r%{svn_rev}.zip"
(cd .. && zip -SrX9 "%{_sourcedir}/%{name}-%{version}-r%{svn_rev}.zip" "%{name}-%{version}")
%endif

# make sure configure is updated to properly support OS/2
bootstrap

%build

# we don't have makeinfo/help2man yet; fake them (this will wipe docs out)
export MAKEINFO=:
export HELP2MAN=:

%configure  --prefix=%{_prefix}                 \
            --exec-prefix=%{_prefix}            \
            --bindir=%{_bindir}                 \
            --sbindir=%{_sbindir}               \
            --sysconfdir=%{_sysconfdir}         \
            --datadir=%{_datadir}               \
            --includedir=%{_includedir}         \
            --libdir=%{_libdir}                 \
            --libexecdir=%{_libexecdir}         \
            --localstatedir=%{_localstatedir}   \
            --mandir=%{_mandir}                 \
            --infodir=%{_infodir}

## build not smp safe:
make # %%{?_smp_mflags}

#for i in ChangeLog.1997 ChangeLog.1998 ChangeLog.1999 ChangeLog.2002; do
#  iconv -f ISO_8859-15 -t UTF8 $i > $i.tmp
#  mv -f $i.tmp $i
#done

#%check
#make check VERBOSE=yes

%install
rm -rf ${buildroot}
make install DESTDIR=%{buildroot}

# info's TOP dir (by default owned by info)
rm -f %{buildroot}%{_infodir}/dir
# *.la *.a files generated by libtool shouldn't be distributed (and the
# `./configure --disable-static' breaks testsuite)
rm -f %{buildroot}%{_libdir}/libltdl.la
rm -f %{buildroot}%{_libdir}/ltdl.a

#%post
#/sbin/install-info %{_infodir}/libtool.info.gz %{_infodir}/dir || :

#%preun
#if [ "$1" = 0 ]; then
#   /sbin/install-info --delete %{_infodir}/libtool.info.gz %{_infodir}/dir || :
#fi

%files
%defattr(-,root,root)
%doc AUTHORS COPYING NEWS README THANKS TODO ChangeLog*
#%{_infodir}/libtool.info*.gz
%{_mandir}/man1/libtool.1*
%{_mandir}/man1/libtoolize.1*
%{_bindir}/libtool
%{_bindir}/libtoolize
%{_datadir}/aclocal/*.m4
%exclude %{_datadir}/libtool/libltdl
%{_datadir}/libtool

%files ltdl
%defattr(-,root,root)
%doc libltdl/COPYING.LIB
%{_libdir}/ltdl*.dll

%files ltdl-devel
%defattr(-,root,root)
%doc libltdl/README
%{_datadir}/libtool/libltdl
%{_includedir}/ltdl.h
%{_includedir}/libltdl
# Import libraries must be in -devel subpackage
%{_libdir}/ltdl*_dll.a

%files debug
%defattr(-,root,root)
%{_libdir}/*.dbg

%changelog
* Thu Sep 04 2014 yd
- added debug package with symbolic info for exceptq.

* Wed Sep 3 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-3
- Rebuild with autoconf 2.69-2.
- Use /@unixroot in generated files instead of absolute paths to
  compiler files.

* Mon Sep 1 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-2
- Fix PATH_SEPARATOR detection in libtoolize.

* Sun Aug 31 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-1
- Initial package for version 2.4.2.
