--- Makefile    	2021-07-19 19:21:36.000000000 +0100
+++ Makefile_new	2021-07-19 19:20:42.000000000 +0100
@@ -29,7 +29,7 @@
 BLDLEVEL_VERSION_MACRO := KAI_VERSION
 BLDLEVEL_VERSION_FILE := kai.h
 BLDLEVEL_VERSION := $(shell sed -n -e "s/^[ \t]*\#[ \t]*define[ \t]\+$(BLDLEVEL_VERSION_MACRO)[ \t]\+\"\(.*\)\"/\1/p" $(BLDLEVEL_VERSION_FILE))
-BLDLEVEL_DATE := $(shell LANG=C date +"\" %F %T %^Z  \"")
+BLDLEVEL_DATE := $(shell LANG=C date +"\" %d %b %Y %H:%M:%S\ \ \ \ \ \"")
 BLDLEVEL_HOST = $(shell echo $(HOSTNAME) | cut -b -11)
 BLDLEVEL := @\#$(BLDLEVEL_VENDOR):$(BLDLEVEL_VERSION)\#@\#\#1\#\#$(BLDLEVEL_DATE)$(BLDLEVEL_HOST)::::::@@
 
@@ -66,11 +66,11 @@
 
 $(KAIDLL): $(OBJS) $(KAIDLLDEF)
 	$(CC) -Zdll $(LDFLAGS) -o $@ $^
-	echo $(BLDLEVEL)K Audio Interface >> $@
 
 $(KAIDLLDEF):
 	echo LIBRARY $(KAIDLLNAME) INITINSTANCE TERMINSTANCE > $@
 	echo DATA MULTIPLE NONSHARED >> $@
+	echo DESCRIPTION "\"$(BLDLEVEL)K Audio Interface\"" >> $@
 
 kaidemo.exe : kaidemo.o kai.lib
 	$(CC) $(LDFLAGS) -o $@ $^ -lmmpm2
