# See the bug #429880
%global gcc_major  %(gcc -dumpversion || echo "666")
# See rhbz#1193591
%global automake_version %(set -- `automake --version | head -n 1` ; echo ${4-unknown})

# TODO make check takes insanely long when run by rpmbuild on OS/2.
%bcond_with check

Summary: The GNU Portable Library Tool
Name:    libtool
Version: 2.4.6
Release: 4%{?dist}
License: GPLv2+ and LGPLv2+ and GFDL
URL:     http://www.gnu.org/software/libtool/
Vendor:  bww bitwise works GmbH

%scm_source github http://github.com/bitwiseworks/%{name}-os2 60849038f64e593bd4a8deda5321488a0c90786c
#scm_source git file://D:/Coding/%{name}/master 6084903

BuildRequires: make git zip

%info_requires

# /usr/bin/libtool includes paths within gcc's versioned directories
# Libtool must be rebuilt whenever a new upstream gcc is built
# Starting with gcc 7 gcc in Fedora is packaged so that only major
# number changes need libtool rebuilding.
Requires: gcc(major) = %{gcc_major}
Requires: autoconf, automake, sed, tar, findutils

BuildRequires: gcc(major) = %{gcc_major}
BuildRequires: texinfo
BuildRequires: autoconf, automake
BuildRequires: help2man

# make sure we can configure all supported langs
BuildRequires: libstdc++-devel
# TODO no gfortran yet
# gcc-gfortran

BuildRequires: gcc, gcc-c++


%description
GNU Libtool is a set of shell scripts which automatically configure UNIX and
UNIX-like systems to generically build shared libraries. Libtool provides a
consistent, portable interface which simplifies the process of using shared
libraries.

If you are developing programs which will use shared libraries, but do not use
the rest of the GNU Autotools (such as GNU Autoconf and GNU Automake), you
should install the libtool package.

The libtool package also includes all files needed to integrate the GNU
Portable Library Tool (libtool) and the GNU Libtool Dynamic Module Loader
(ltdl) into a package built using the GNU Autotools (including GNU Autoconf
and GNU Automake).


%package ltdl
Summary:  Runtime libraries for GNU Libtool Dynamic Module Loader
Provides: %{name}-libs = %{version}-%{release}
License:  LGPLv2+


%description ltdl
The libtool-ltdl package contains the GNU Libtool Dynamic Module Loader, a
library that provides a consistent, portable interface which simplifies the
process of using dynamic modules.

These runtime libraries are needed by programs that link directly to the
system-installed ltdl libraries; they are not needed by software built using
the rest of the GNU Autotools (including GNU Autoconf and GNU Automake).


%package ltdl-devel
Summary: Tools needed for development using the GNU Libtool Dynamic Module Loader
Requires: automake = %automake_version
Requires: %{name}-ltdl = %{version}-%{release}
License:  LGPLv2+


%description ltdl-devel
Static libraries and header files for development with ltdl.


%debug_package


%prep
%scm_setup

# Make sure configure is updated to properly support OS/2
# (slashes in PATH are needed for the bootstrap script itself)
export PATH=`echo $PATH | tr '\\\\' /`
./bootstrap --copy --force --skip-git

# Restore .version and ChangeLog as they are not properly regenerated (they need .git)
rm -f .version ChangeLog
mv .version~ .version
mv ChangeLog~ ChangeLog


%build

export CC=gcc
export CXX=g++
export F77=gfortran
export CFLAGS="$RPM_OPT_FLAGS"

# These are for LTDL DLL
export LDFLAGS="-Zomf -Zmap -Zhigh-mem"

%configure  --prefix=%{_prefix}                 \
            --exec-prefix=%{_prefix}            \
            --bindir=%{_bindir}                 \
            --sbindir=%{_sbindir}               \
            --sysconfdir=%{_sysconfdir}         \
            --datadir=%{_datadir}               \
            --includedir=%{_includedir}         \
            --libdir=%{_libdir}                 \
            --libexecdir=%{_libexecdir}         \
            --localstatedir=%{_localstatedir}   \
            --mandir=%{_mandir}                 \
            --infodir=%{_infodir}

make %{?_smp_mflags}


%check
%if %{with check}
make check VERBOSE=yes || { cat testsuite.log ; false ; }
%endif


%install
rm -rf ${buildroot}
make install DESTDIR=%{buildroot}
# info's TOP dir (by default owned by info)
rm -f %{buildroot}%{_infodir}/dir
# *.la *.a files generated by libtool shouldn't be distributed (and the
# `./configure --disable-static' breaks testsuite)
rm -f %{buildroot}%{_libdir}/libltdl.la
rm -f %{buildroot}%{_libdir}/ltdl.a


%clean
rm -rf $RPM_BUILD_ROOT


%post
%info_post %{name}.info


%preun
%info_preun %{name}.info


%files
%license COPYING
%doc AUTHORS NEWS README THANKS TODO ChangeLog*
%{_infodir}/libtool.info*.gz
%{_mandir}/man1/libtool.1*
%{_mandir}/man1/libtoolize.1*
%{_bindir}/libtool
%{_bindir}/libtoolize
%{_datadir}/aclocal/*.m4
%dir %{_datadir}/libtool
%{_datadir}/libtool/build-aux


%files ltdl
%license libltdl/COPYING.LIB
%{_libdir}/ltdl*.dll


%files ltdl-devel
%license libltdl/COPYING.LIB
%doc libltdl/README
%{_datadir}/libtool
%exclude %{_datadir}/libtool/build-aux
%{_includedir}/ltdl.h
%{_includedir}/libltdl
# Import libraries must be in -devel subpackage
%{_libdir}/ltdl*_dll.a


%changelog
* Tue Jan 14 2020 Dmitriy Kuminov <coding@dmik.org> 2.4.6-4
- Use scm_ macros.
- Resync with latest Fedora spec (11bb551).
- Rebuild for GCC 9.
- Add support for LT_BUILDLEVEL [#1].

* Mon Nov 28 2016 Dmitriy Kuminov <coding@dmik.org> 2.4.6-3
- Add -buildlevel command line option to pass BUILDLEVEL signature
  for DLL creation.
- Fix NEED_USCORE detection in ltdl (LT_FUNC_DLSYM_USCORE) on OS/2.
- Build LTDL DLL with high memory support (-Zhigh-mem).

* Tue Feb 2 2016 Dmitriy Kuminov <coding@dmik.org> 2.4.6-2
- Fix missing DLL exports when -export-symbols-regex is given.
- Fix broken -os2dllname compatiblity.
- Set libext to lib when AR is emxomfar.
- Make SYMBOL_UNDERSCORE correctly defined.

* Tue Feb 17 2015 Dmitriy Kuminov <coding@dmik.org> 2.4.6-1
- Update to version 2.4.6 from vendor.

* Fri Jan 23 2015 yd
- rebuild for gcc 4.9.2.

* Tue Jan 13 2015 Dmitriy Kuminov <coding@dmik.org> 2.4.2-8
- Support -release option on OS/2.
- Use response files for long command lines when linking DLLs on OS/2.

* Fri Oct 31 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-7
- Rename -os2dllname switch to -shortname (old one is still
  supported for backward compatibility).
- Always set allow_undefined to no on OS/2.
- Fix setting BEGINLIBPATH in execute mode on OS/2.
- Support -version-number on OS/2.

* Tue Oct 3 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-6
- Generate proper DLL version suffix (CURRNENT - AGE).

* Tue Sep 30 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-5
- Fix weird typo breaking correct OS/2 DLL name generation
  in some cases.

* Thu Sep 04 2014 yd
- added debug package with symbolic info for exceptq.

* Wed Sep 3 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-3
- Rebuild with autoconf 2.69-2.
- Use /@unixroot in generated files instead of absolute paths to
  compiler files.

* Mon Sep 1 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-2
- Fix PATH_SEPARATOR detection in libtoolize.

* Sun Aug 31 2014 Dmitriy Kuminov <coding@dmik.org> 2.4.2-1
- Initial package for version 2.4.2.
