Summary: The GNU versions of find utilities (find and xargs)
Name: findutils
Version: 4.7.0
Release: 1%{?dist}
Epoch: 1
License: GPLv3+
URL: http://www.gnu.org/software/findutils/
%if !0%{?os2_version}
Source0: https://ftp.gnu.org/pub/gnu/%{name}/%{name}-%{version}.tar.xz

# do not build locate
Patch1:  findutils-4.5.15-no-locate.patch

# add -xautofs option to not descend into directories on autofs file systems
Patch2:  findutils-4.4.2-xautofs.patch

# eliminate compile-time warnings
Patch3:  findutils-4.5.13-warnings.patch

# test-lock: disable the rwlock test
Patch4:  findutils-4.6.0-test-lock.patch

# implement the -noleaf option of find (#1252549)
Patch5:  findutils-4.6.0-leaf-opt.patch

# make upstream test-suite work with root privileges (#1799064)
Patch6:  findutils-4.7.0-root-tests.patch

# simplify leaf optimization for XFS (#1823247)
Patch7:  findutils-4.7.0-leaf-opt-xfs.patch

Conflicts: filesystem < 3
Provides: /bin/find
Provides: bundled(gnulib)
%else
Vendor:  bww bitwise works GmbH
%scm_source github http://github.com/bitwiseworks/%{name}-os2 v%{version}-os2
%endif

BuildRequires: automake
%if !0%{?os2_version}
BuildRequires: dejagnu
%endif
BuildRequires: gettext-devel
BuildRequires: gcc
BuildRequires: git
%if !0%{?os2_version}
BuildRequires: libselinux-devel
%endif
BuildRequires: texinfo
BuildRequires: make

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a file name pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%if 0%{?os2_version}
%debug_package
%endif

%prep
%if !0%{?os2_version}
%autosetup -N -S git

# drop the source code of locate
git rm -q -r locate
git commit -q -m "drop the source code of locate"

# remove ignored files from git and mark them as ignored
tee -a .gitignore << EOF
*~
Makefile.in
/aclocal.m4
/autom4te.cache
/build
/configure
/doc/find.info*
/doc/stamp-vti
/doc/version.texi
EOF
git rm -q -r --cached .
git add --all .
git commit -m "remove ignored files from git"

# apply all patches
%autopatch
%else
%scm_setup
%endif

# replace weirdo constant in gnulib tests causing test failures on armv7hl
%if !0%{?os2_version}
sed -e 's/1729576/EPERM/' \
    -i gnulib-tests/test-{perror2,strerror_r}.c
%endif

# needed because of findutils-4.5.15-no-locate.patch
autoreconf -fiv
%if !0%{?os2_version}
git add --all .
git commit -q -m "after invocation of autoreconf"
%endif

%build
# disable -flto on ppc64le to make test-float pass (#1789115)
%ifarch ppc64le
export CFLAGS="$RPM_OPT_FLAGS -fno-lto"
%endif
%if 0%{?os2_version}
export LDFLAGS="-Zhigh-mem -Zomf -Zargs-wild -Zargs-resp"
export LIBS="-lcx -lpthread"
%endif

mkdir build
cd build
%global _configure ../configure
%configure

%if !0%{?os2_version}
%make_build
%else
make %{?_smp_mflags}
%endif

%check
%if 0%{?os2_version}
# one day we should fix em all
XFAIL_TESTS="test-canonicalize.exe test-dup2.exe test-getdtablesize.exe test-lock.exe"
XFAIL_TESTS="$XFAIL_TESTS test-nstrftime.exe test-select-in.sh test-select-out.sh test-wctype-h.exe"
export XFAIL_TESTS
%endif
make %{?_smp_mflags} check -C build V=1

%install
%make_install -C build

rm -f %{buildroot}%{_infodir}/dir

%if 0%{?os2_version}
# yd move conflicting tools to libexec/bin and place a symlink for script compatibility
mkdir -p $RPM_BUILD_ROOT%{_libexecdir}/bin
for i in find; do
  mv $RPM_BUILD_ROOT%{_bindir}/$i.exe $RPM_BUILD_ROOT%{_libexecdir}/bin/$i.exe
  ln -s %{_libexecdir}/bin/$i.exe $RPM_BUILD_ROOT%{_bindir}/$i
done
%endif

%find_lang %{name}

%files -f %{name}.lang
%{!?_licensedir:%global license %%doc}
%license COPYING
%doc AUTHORS NEWS README THANKS TODO
%{_bindir}/find
%if !0%{?os2_version}
%{_bindir}/xargs
%else
%{_bindir}/xargs.exe
%{_bindir}/locate.exe
%{_bindir}/updatedb
%{_libexecdir}/frcode.exe
%{_libexecdir}/bin/find.exe
%endif
%{_mandir}/man1/find.1*
%{_mandir}/man1/xargs.1*
%{_infodir}/find.info*
%{_infodir}/find-maint.info.*
%if 0%{?os2_version}
%{_mandir}/man1/locate.1*
%{_mandir}/man1/updatedb.1*
%{_mandir}/man5/locatedb.5*
%endif

%changelog
* Wed Dec 23 2020 Silvan Scherrer <silvan.scherrer@aroa.ch> - 4.7.0-1
- update to version 4.7.0
- resync with fedora spec

* Mon Oct 24 2016 Silvan Scherrer <silvan.scherrer@aroa.ch> - 4.6.0-2
- fix locate --statistics
- use ; as path seperator

* Wed Oct 05 2016 Silvan Scherrer <silvan.scherrer@aroa.ch> - 4.6.0-1
- udated version to 4.6.0
- adjusted spec to latest toolset

* Sat Mar 15 2014 yd
- fixed libexec dir for symlinks.
- added debug package with symbolic info for exceptq.

* Tue Jul 30 2013 yd
- disabled FTS code, now find works as before.

* Wed Jul 24 2013 yd
- move conflicting tools to libexec/bin.

* Wed Jun 05 2013 yd
- r641, fix xargs stop in freadahead.

* Thu Mar 14 2013 yd
- rename find.exe to find-unix.exe and add symlink.

* Sun Jan 08 2012 yd
- initial unixroot build
